Silence pipe errors on println!()
Use writeln!() instead so that it can check the return value and stop.

  $ cargo run target/debug/inlinestat | head
     Compiling inlinestat v0.1.0 (/home/namhyung/project/inlinestat)
      Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.47s
       Running `target/debug/inlinestat target/debug/inlinestat`
  # Total Sz    Self Sz  Inlines   Function Name
          69         69        0   fmt
          45         45        0   fmt
          26         26        0   eq
          22         22        0   eq
         339        162        4   runtime
         222         87        6   encode_utf8_raw
         349        216        7   encode_utf8_raw_unchecked
          28         28        0   ne<object::pe::Guid, object::pe::Guid>
          40         35        1   index<object::pe::ImageSymbolBytes, core::ops::range::RangeFull, 0>

  thread 'main' (44570) panicked at library/std/src/io/stdio.rs:1165:9:
  failed printing to stdout: Broken pipe (os error 32)
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Signed-off-by: Namhyung Kim <namhyung@gmail.com>